// 최상위 레이아웃 페이지
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

// header 컴포넌트 참조하기
import Hearder from "@/app/ui/header";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}></body>
      <main className="flex min-h-screen flex-col items-center p-24">
        {/* 헤더 컴포넌트 사용 */}
        <Hearder />

        <div className="mt-20">{children}</div>
      </main>
    </html>
  );
}
